before_script:
        - apt-get update -qy
        - apt-get install -y python-dev python-pip

stages:
        - build
        - test

syntax-check:
        stage: build
        script:
                - python -m compileall ./

style-check:
        stage: test
        script: 
                - pip install black
                - black --check .
