image: python:3

stages:
        - test
        - deploy

style-check:
        stage: test
        before_script:
        - pip install black
        script:
        - black --check .
        allow_failure: true

deploy-to-server:
        stage: deploy
        script:
                - mkdir -p ~/.ssh
                - echo "$SSH_HOST_VERIFICATION" | base64 -d > ~/.ssh/known_hosts
                - echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa
                - chmod -R 700 ~/.ssh
                - ssh gitlab@$CONTAINER_IP "sh -c 'cd rubber-duck && ./deploy-entry.sh'"
        only:
                - master@rpi-academic-discord/slithering-duck
