image: python:3

stages:
        - test
        - deploy

style-check:
        stage: test
        before_script:
        - pip install black
        script:
        - black --check .
        allow_failure: true

deploy-to-server:
        stage: deploy
        script:
                - mkdir -p ~/.ssh
                - echo "$SSH_HOST_VERIFICATION" | base64 -d > ~/.ssh/known_hosts
                - echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa
                - chmod -R 700 ~/.ssh
                - for user in $BOT_USERS; do ssh 34.74.236.201 "sh -c 'sudo runuser -u $user -- sh -c \"cd /home/$user/$user && ./deploy-entry.sh\"'" & ; done
        only:
                - master@rpi-academic-discord/slithering-duck
