image: python:3

stages:
        - test
        - deploy

style-check:
        stage: test
        before_script:
                - pip install black
        script:
                - black --check .
        allow_failure: true

pylint:
        stage: test
        before_script:
                - pip install pylint pylint_junit
                - pip install -r requirements.txt # required for checking imports
        script:
                - pylint --version
                - pylint --rcfile .pylintrc bot --output-format=pylint_junit.JUnitReporter | tee pylint.xml
        artifacts:
                reports:
                        junit:
                                pylint.xml

mypy:
        stage: test
        before_script:
                - pip install mypy
                - pip install -r requirements.txt
        script:
                - mypy main.py --strict --ignore-missing-imports --junit-xml mypy.xml
        artifacts:
                reports:
                        junit:
                                mypy.xml

deploy-to-server:
        stage: deploy
        script:
                - mkdir -p ~/.ssh
                - echo "$SSH_HOST_VERIFICATION" | base64 -d > ~/.ssh/known_hosts
                - echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa
                - chmod -R 700 ~/.ssh
                - for user in $BOT_USERS; do ssh gitlab@$CONTAINER_IP "sh -c 'sudo runuser -u $user -- sh -c \"cd /home/$user/$user && ./deploy-entry.sh\"'"; done
        only:
                - master@rpi-academic-discord/slithering-duck
