image: python

stages:
        - build
        - test
        - deploy

syntax-check:
        stage: build
        script:
                - python -m compileall ./

style-check:
        stage: test
        script: 
                - pip install black
                - black --check .
        allow_failure: true

deploy-to-server:
        stage: deploy
        script:
                - mkdir -p ~/.ssh
                - echo "$SSH_HOST_VERIFICATION" | base64 -d > ~/.ssh/known_hosts
                - echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa
                - chmod -R 700 ~/.ssh
                - ssh gitlab@$CONTAINER_IP "cd rubber-duck && git pull && sudo pip3 install -r requirements.txt && rename 's/\.example$//' config/* && pidof python3 | xargs | BOT_TOKEN=$BOT_TOKEN python3 main.py &"
