image: python

stages:
        - build
        - test

syntax-check:
        stage: build
        script:
                - python -m compileall ./

style-check:
        stage: test
        script: 
                - pip install black
                - black --check .
