image: python

stages:
        - test

style-check:
        stage: test
        script:
                - pip install black
                - black --check .
        allow_failure: true

test-suite:
        stage: test
        script:
                - pip install -r requirements.txt
                - python -m unittest bot.tests
